openapi: "3.1.0"
info:
  title: "MyAPI"
  version: "2024.7.6"
servers:
- description: "test"
  url: "https://myserver/app"
security:
- SpsBearer: []
paths:
  /files:
    get:
      responses:
        "200":
          description: "Success"
components:
  securitySchemes:
    SpsBearer:
      type: http
      scheme: bearer
      description: |-
        Test Bearer authentication specifies a bearer token in the 'Authorization' header following the format:
        Authorization: Bearer <token>